#ifndef CONSTANT_H
#define CONSTANT_H

#define DEFAULT_GKERNEL 3
#define DEFAULT_GSIGMA 5
#define DEFAULT_MIDKERNEL 3
#define DEFAULT_MORPHKERNEL 3
#define DEFAULT_ZFACTOR 0.06
#define DEFAULT_CONTRA 1.5
#define DEFAULT_BLENDA 0.6



#endif // CONSTANT_H
